version: '2'
services:
  lockchecker:
    build: .
    image: idrs-python:0.1
    volumes:
      - .:/script
    depends_on:
      - epdserver
    env_file:
      - /etc/environment
    privileged: true
    command: '/bin/bash -c "cd /script && ./lockchecker.py"'
  ssddetector:
    build: .
    image: idrs-python:0.1
    volumes:
      - .:/script
    env_file:
      - /etc/environment
    privileged: true
    command: '/bin/bash -c "cd /script && ./ssddetector.py"'
  epdserver:
    build: .
    image: idrs-python:0.1
    volumes:
      - .:/script
    ports:
          - "8081:8081"
    env_file:
      - /etc/environment
    environment:
      TZ: "Asia/Toyko"
    privileged: true
    command: '/bin/bash -c "cd /script && ./epdserver.py"'
